# docker-compose.yaml
  version: '3.8'
  services:
    jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
        - 8080:8080
        - 50000:50000
      container_name: my_jenkins
      volumes:
        - /Users/WRR/Documents/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
    agent:
      image: jenkins/ssh-agent:jdk11
      privileged: true
      user: root
      container_name: agent_jdk11
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      expose:
        - 22
      environment:
        - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDE/qmPrVBiMgsROJbKoKgpbVZWQfcp2tH0d/qObhHo428IByd10io/trCJPOrSstGkcgj8PNSwfyDNmDfKzAa4S9do/p+FTQC23+HDpP9+N1B4ZAIdjfjJSpHZyk7PNtIVZ+G4Aq2vqj3S+GvVJM0ZISiq8zldLS9IJ0PDxtCXSl9a67/oqESwmJ6n0Xz1jNRfgvLR8sC+Ym2JIKvPDHpVk2EebZGeD2Z6S3e3vk+es8ODAybyLG3RwNrI9iWCoc1Z3k/IFf+P4JYhSwGbHCrKiI9e3KMvJOxCA+MSjmm55b6hOke+U3ef3oxu4X2PKPukCBCx8BAmGbQkTtTrpgoXy3B9RBkhhfIsaCbc2AT8dPf12IBnXdtHgz/cAGnH7zs3HPmac9IdTPmEy5iqwtONI8gSgvggVRmARonU0gbvCb9Ie6OyraYH4sSNkujWTUiBkxpC5BwEaXr2bhWFRMoS/tJXeWvPccMnmr4qw7L7Xj0vVhlsWdIiLeeA0hQ4ntE= WRR@WRR-Macbook.local

      